
name: 'NX'

on:
  push:
    branches:
      - master
  pull_request:
jobs:
  nx:
    name: NX lint build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - run: npm i -g @nestjs/cli
      - uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: lint,build,test,deploy
